### ISSUE TITLE
api docs not rendering fully

### ISSUE THREAD

**Issue by sjsrey** [pysal/segregation#58]
Compare [segregation](https://segregation.readthedocs.io/en/latest/api.html) with [giddy](https://giddy.readthedocs.io/en/latest/api.html).

**Comment by renanxcortes** [comment]
hm... I still didn't find a way to fix this, but I have a strong feeling that it broke because we changed entirely the api of the segregation module recently. So, instead of for example `segregation.non_spatial_indexes.Dissim` simply does not exist anymore. Now it is `segregation.aspatial.Dissim`.

The current doc that it is generated is with the old API:
![image](https://user-images.githubusercontent.com/22593188/59570390-238f0300-904c-11e9-8b23-94c6c2af492b.png)

How can I create a new set of files @knaaptime ?

**Comment by renanxcortes** [comment]
Do I need to run `conf.py`?

**Comment by sjsrey** [comment]
> Do I need to run `conf.py`?

If you update the api.rst file, and then run `make html` it should regenerate those rst files.

**Comment by renanxcortes** [comment]
After fixing locally the html that sphinx generated locally and everything is fixed and pushed. However, I'm facing many other issues in the sphinx internal building. After figuring out that I neede to add sphinx_bootstrap_theme also in the requirements.txt (https://github.com/pysal/segregation/pull/66/commits/6a535096087e149ebadfb9f83be90e3293004191) I'm running now in this issue:

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/checkouts/latest/doc/conf.py", line 25, in <module>
    import segregation
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/__init__.py", line 8, in <module>
    from . import spatial
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/__init__.py", line 1, in <module>
    from .spatial_indexes import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/spatial_indexes.py", line 10, in <module>
    import libpysal
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/__init__.py", line 28, in <module>
    from . import io
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/__init__.py", line 3, in <module>
    from .iohandlers import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/__init__.py", line 4, in <module>
    from . import gwt
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/gwt.py", line 3, in <module>
    from ...weights.weights import W
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/__init__.py", line 2, in <module>
    from .distance import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/distance.py", line 7, in <module>
    from .util import isKDTree, get_ids, get_points_array_from_shapefile,\
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/util.py", line 17, in <module>
    import geopandas as gpd
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/geoseries.py", line 13, in <module>
    from geopandas.base import GeoPandasBase, _unary_op, _CoordinateIndexer
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/base.py", line 17, in <module>
    from rtree.core import RTreeError
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/checkouts/latest/doc/conf.py", line 25, in <module>
    import segregation
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/__init__.py", line 8, in <module>
    from . import spatial
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/__init__.py", line 1, in <module>
    from .spatial_indexes import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/spatial_indexes.py", line 10, in <module>
    import libpysal
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/__init__.py", line 28, in <module>
    from . import io
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/__init__.py", line 3, in <module>
    from .iohandlers import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/__init__.py", line 4, in <module>
    from . import gwt
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/gwt.py", line 3, in <module>
    from ...weights.weights import W
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/__init__.py", line 2, in <module>
    from .distance import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/distance.py", line 7, in <module>
    from .util import isKDTree, get_ids, get_points_array_from_shapefile,\
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/util.py", line 17, in <module>
    import geopandas as gpd
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/geoseries.py", line 13, in <module>
    from geopandas.base import GeoPandasBase, _unary_op, _CoordinateIndexer
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/base.py", line 17, in <module>
    from rtree.core import RTreeError
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/checkouts/latest/doc/conf.py", line 25, in <module>
    import segregation
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/__init__.py", line 8, in <module>
    from . import spatial
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/__init__.py", line 1, in <module>
    from .spatial_indexes import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/segregation/spatial/spatial_indexes.py", line 10, in <module>
    import libpysal
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/__init__.py", line 28, in <module>
    from . import io
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/__init__.py", line 3, in <module>
    from .iohandlers import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/__init__.py", line 4, in <module>
    from . import gwt
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/io/iohandlers/gwt.py", line 3, in <module>
    from ...weights.weights import W
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/__init__.py", line 2, in <module>
    from .distance import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/distance.py", line 7, in <module>
    from .util import isKDTree, get_ids, get_points_array_from_shapefile,\
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/libpysal/weights/util.py", line 17, in <module>
    import geopandas as gpd
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/geoseries.py", line 13, in <module>
    from geopandas.base import GeoPandasBase, _unary_op, _CoordinateIndexer
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/geopandas/base.py", line 17, in <module>
    from rtree.core import RTreeError
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/envs/latest/lib/python3.7/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```

which I believe is similar to one discussed in https://github.com/pysal/spaghetti/issues/268. I'm still trying to debug this. If you have any clue how to do this @weikang9009 and @jGaboardi I appreciate it! Thanks!

**Comment by renanxcortes** [comment]
After following https://github.com/pysal/spaghetti/pull/272/commits/4d73cf536e04d3114594e41470329c0b3874acdb#diff-0112b253036ac23d3e0ac498694769d7 and adding conda in `readthedocs.yml`

The new error is

```
Processing /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/checkouts/latest
  WARNING: segregation 1.0.6 does not provide the extra 'docs'
  WARNING: segregation 1.0.6 does not provide the extra 'tests'
Requirement already up-to-date: pandas in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.24.2)
Collecting geopandas (from segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/74/42/f4b147fc7920998a42046d0c2e65e61000bc5d104f1f8aec719612cb2fc8/geopandas-0.5.0-py2.py3-none-any.whl
Requirement already up-to-date: matplotlib in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (3.1.0)
Requirement already up-to-date: scikit-learn in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.21.2)
Requirement already up-to-date: seaborn in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.9.0)
Requirement already up-to-date: numpy in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (1.16.4)
Collecting scipy (from segregation==1.0.6)
  Downloading https://files.pythonhosted.org/packages/72/4c/5f81e7264b0a7a8bd570810f48cd346ba36faedbd2ba255c873ad556de76/scipy-1.3.0-cp36-cp36m-manylinux1_x86_64.whl (25.2MB)
Requirement already up-to-date: libpysal in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (4.1.0)
Requirement already up-to-date: osmnx in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.10)
Requirement already up-to-date: pandana in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.4.1)
Requirement already up-to-date: urbanaccess in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from segregation==1.0.6) (0.2.0)
Collecting sphinx_bootstrap_theme (from segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/a9/b8/ebcd1a7c579eb85929bbfd54617c5c484ba8cd78e4d3499d749e64b5ad3b/sphinx-bootstrap-theme-0.7.1.tar.gz
Requirement already up-to-date: python-dateutil>=2.5.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from pandas->segregation==1.0.6) (2.8.0)
Requirement already up-to-date: pytz>=2011k in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from pandas->segregation==1.0.6) (2019.1)
Collecting fiona (from geopandas->segregation==1.0.6)
  Downloading https://files.pythonhosted.org/packages/89/4a/193cd6a75e51062c85f4e1cd6f312b3bbda6e26ba7510f152ef5016f0b16/Fiona-1.8.6-cp36-cp36m-manylinux1_x86_64.whl (17.9MB)
Collecting shapely (from geopandas->segregation==1.0.6)
  Downloading https://files.pythonhosted.org/packages/38/b6/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m-manylinux1_x86_64.whl (1.5MB)
Collecting pyproj (from geopandas->segregation==1.0.6)
  Downloading https://files.pythonhosted.org/packages/ac/1a/81ef33d97354eb7d1765a921ecaf2ece41fd7927937b7c74124b6a2a0d99/pyproj-2.2.0-cp36-cp36m-manylinux1_x86_64.whl (11.2MB)
Requirement already up-to-date: cycler>=0.10 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from matplotlib->segregation==1.0.6) (0.10.0)
Requirement already up-to-date: kiwisolver>=1.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from matplotlib->segregation==1.0.6) (1.1.0)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from matplotlib->segregation==1.0.6) (2.4.0)
Requirement already up-to-date: joblib>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from scikit-learn->segregation==1.0.6) (0.13.2)
Requirement already up-to-date: Rtree>=0.8.3 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from osmnx->segregation==1.0.6) (0.8.3)
Requirement already up-to-date: networkx>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from osmnx->segregation==1.0.6) (2.3)
Requirement already up-to-date: descartes>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from osmnx->segregation==1.0.6) (1.1.0)
Requirement already up-to-date: requests>=2.21 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from osmnx->segregation==1.0.6) (2.22.0)
Requirement already up-to-date: tables>=3.1.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from pandana->segregation==1.0.6) (3.5.2)
Collecting osmnet>=0.1.2 (from pandana->segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/68/64/ec9b88e7cb694b33a1adf9822e40e513d6676a122121769d8ccdd773596f/osmnet-0.1.5-py2.py3-none-any.whl
Requirement already up-to-date: cython>=0.25.2 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from pandana->segregation==1.0.6) (0.29.10)
Requirement already up-to-date: six>=1.11 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from urbanaccess->segregation==1.0.6) (1.12.0)
Requirement already up-to-date: geopy>=1.11.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from urbanaccess->segregation==1.0.6) (1.20.0)
Collecting pyyaml>=3.11 (from urbanaccess->segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz
Requirement already up-to-date: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from sphinx_bootstrap_theme->segregation==1.0.6) (41.0.1)
Requirement already up-to-date: cligj>=0.5 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from fiona->geopandas->segregation==1.0.6) (0.5.0)
Requirement already up-to-date: attrs>=17 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from fiona->geopandas->segregation==1.0.6) (19.1.0)
Requirement already up-to-date: click-plugins>=1.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from fiona->geopandas->segregation==1.0.6) (1.1.1)
Requirement already up-to-date: click<8,>=4.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from fiona->geopandas->segregation==1.0.6) (7.0)
Requirement already up-to-date: munch in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from fiona->geopandas->segregation==1.0.6) (2.3.2)
Requirement already up-to-date: decorator>=4.3.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from networkx>=2.3->osmnx->segregation==1.0.6) (4.4.0)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.21->osmnx->segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from requests>=2.21->osmnx->segregation==1.0.6) (3.0.4)
Collecting certifi>=2017.4.17 (from requests>=2.21->osmnx->segregation==1.0.6)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Requirement already up-to-date: idna<2.9,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from requests>=2.21->osmnx->segregation==1.0.6) (2.8)
Requirement already up-to-date: numexpr>=2.6.2 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from tables>=3.1.0->pandana->segregation==1.0.6) (2.6.9)
Requirement already up-to-date: mock>=2.0 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from tables>=3.1.0->pandana->segregation==1.0.6) (3.0.5)
Requirement already up-to-date: geographiclib<2,>=1.49 in /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/conda/latest/lib/python3.6/site-packages (from geopy>=1.11.0->urbanaccess->segregation==1.0.6) (1.49)
Building wheels for collected packages: segregation, sphinx-bootstrap-theme, pyyaml
  Building wheel for segregation (setup.py): started
  Building wheel for segregation (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-vnox4udc/wheels/e2/21/dd/56e76a047f4a942b82d67fbb6dd62c07a9fb86225d253d532d
  Building wheel for sphinx-bootstrap-theme (setup.py): started
  Building wheel for sphinx-bootstrap-theme (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/.cache/pip/wheels/71/28/10/e04d1ab1110dbde7f436dd159ed5ee35113f66536df6d99a79
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/segregation-renan/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built segregation sphinx-bootstrap-theme pyyaml
Installing collected packages: fiona, shapely, pyproj, geopandas, scipy, sphinx-bootstrap-theme, segregation, osmnet, pyyaml, urllib3, certifi
  Found existing installation: Fiona 1.8.4
    Uninstalling Fiona-1.8.4:
      Successfully uninstalled Fiona-1.8.4
  Found existing installation: Shapely 1.6.4.post1
    Uninstalling Shapely-1.6.4.post1:
      Successfully uninstalled Shapely-1.6.4.post1
  Found existing installation: pyproj 1.9.6
    Uninstalling pyproj-1.9.6:
      Successfully uninstalled pyproj-1.9.6
  Found existing installation: geopandas 0.4.1
    Uninstalling geopandas-0.4.1:
      Successfully uninstalled geopandas-0.4.1
  Found existing installation: scipy 1.2.1
    Uninstalling scipy-1.2.1:
      Successfully uninstalled scipy-1.2.1
  Found existing installation: osmnet 0.1.4
    Uninstalling osmnet-0.1.4:
      Successfully uninstalled osmnet-0.1.4
  Found existing installation: PyYAML 5.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I think that perhaps adding a `--ignore-installed` somewhere would do the trick (at least for this part).

I'm still trying to debug (I've been doing other stuffs in other of my local branches but unsuccessfully) the current built is being performed in https://github.com/renanxcortes/segregation/tree/rtd_test_from_pysal_master.

**Comment by renanxcortes** [comment]
Just wanted to flag that the same issue happens sometimes with `certifi`.

**Comment by renanxcortes** [comment]
EUREKA!!! EUREKA!!! So, after spending some time debugging sphinx I figure out that I could go with the classical `pip` channel instead of the `conda` option.

In summary, the problem was when I use the pip channel I run into `OSError: Could not find libspatialindex_c library file`, on the other hand when I go with the conda channel I run into `ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

It ended that the pip was the one I solved by adding some libraries that depended on C as mock in the beginning of `conf.py` such as explained in https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules. The built ran smoothly! :)

I'm pretty sure that this could be an alternative to https://github.com/pysal/spaghetti/issues/268.

**Comment by weikang9009** [comment]
@renanxcortes [the citations](https://segregation.readthedocs.io/en/latest/generated/segregation.profile.Profile_Spatial_Segregation.html#segregation.profile.Profile_Spatial_Segregation) and [references](https://segregation.readthedocs.io/en/latest/references.html) are not properly rendered or showing up.
![image](https://user-images.githubusercontent.com/7359284/59735749-c641b000-920b-11e9-8256-c9858ed330d5.png)
![Uploading image.png…]()

**Comment by renanxcortes** [comment]
Ow, indeed! I didn't see that! Thanks, @weikang9009 ! I'll take a look at this! It's probably something with the sphinx bibtex library!

**Comment by renanxcortes** [comment]
Fixed now with https://github.com/pysal/segregation/pull/68! :)
(I also moved `numpydoc` from outside of the mock in https://github.com/pysal/segregation/pull/69)
